services:
  - type: web
    name: alexai-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60
      targetCPUPercent: 60
